import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useUser } from '@/contexts/UserContext';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Link } from 'react-router-dom';
import { Button } from './ui/button';
export function Header() {
    const { user } = useUser();
    console.log('Header - current user:', user);
    console.log('Header - localStorage:', localStorage.getItem('userInfo'));
    return (_jsx("header", { className: "bg-amber-50/80 backdrop-blur-sm sticky top-0 z-50 border-b border-amber-300 w-full", children: _jsx("div", { className: "w-full px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between h-16 items-center", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(Link, { to: "/", className: "flex items-center", children: _jsxs("span", { className: "text-2xl font-bold", children: [_jsx("span", { className: "text-amber-600", children: "Training" }), _jsx("span", { className: "text-amber-500", children: "Doc" }), _jsx("span", { className: "text-amber-700", children: "AI" })] }) }) }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(Link, { to: "/ai-chat", className: "text-amber-800 hover:text-amber-900", children: "AI\u5BF9\u8BDD" }), _jsx(Link, { to: "/documents", className: "text-amber-800 hover:text-amber-900", children: "\u6587\u6863\u5386\u53F2" }), _jsx(Link, { to: "/outline", className: "text-amber-800 hover:text-amber-900", children: "\u5927\u7EB2\u751F\u6210" }), _jsx(Link, { to: "/templates", className: "text-amber-800 hover:text-amber-900", children: "\u6A21\u677F\u5E93" }), _jsx(Link, { to: "/employees", className: "text-amber-800 hover:text-amber-900", children: "\u5458\u5DE5\u7BA1\u7406" }), _jsx(Link, { to: "/pricing", className: "text-amber-800 hover:text-amber-900", children: "\u4EF7\u683C" }), user ? (_jsxs(Avatar, { children: [_jsx(AvatarImage, { src: user.avatar, alt: user.email || '' }), _jsx(AvatarFallback, { children: user.email?.[0]?.toUpperCase() || '?' })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/auth", children: _jsx(Button, { variant: "outline", className: "border-amber-400 text-amber-700 hover:bg-amber-100", children: "\u767B\u5F55" }) }), _jsx(Link, { to: "/auth", children: _jsx(Button, { className: "bg-gradient-to-r from-amber-600 to-amber-500 text-white hover:from-amber-700 hover:to-amber-600", children: "\u514D\u8D39\u6CE8\u518C" }) })] }))] })] }) }) }));
}
